import React from 'react';
import PriceorIncomeValue from './pricevalue';
import { styled } from 'styled-components';

const Title = styled.div`
  border-bottom: 1px dashed var(--neutral-gray-200, #000000);
  --tw-text-opacity: 1;
  color: rgb(63 63 70 / var(--tw-text-opacity));
  font-size: 16px;
  font-weight: 500;
  font-family: Poppins;
`;

const CashFlow = () => {
  return (
    <div>
      <Title className="mt-6justify-start items-center inline-flex">
        Cash flow Analysis
      </Title>
      <PriceorIncomeValue label="Rental Income" value="$50000/Month" />
      <PriceorIncomeValue label="Rental Expenses" value="- $30000/Month" />
      <PriceorIncomeValue label="Net Monthly Cashflow" value="$20000/Month" />
      <p className="text-zinc-700 text-sm font-normal font-poppins">
        The cash flow analysis considers the rental income generated by the
        property and deducts the expenses to determine the net cash flow. In
        this case, the property generates a net cash flow of $20,000 per month.
      </p>
    </div>
  );
};

export default CashFlow;
